# Generated by Django 5.0.2 on 2024-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0002_alter_admin_email_alter_admin_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='codEmpleado',
            field=models.CharField(default=2, max_length=3, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='Identificacion',
            field=models.CharField(max_length=12),
        ),
    ]
