# Generated by Django 5.0.2 on 2024-04-29 01:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0003_empleado_codempleado_alter_empleado_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='fecha_registro',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha_cambio',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de Cambio'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='cantidad',
            field=models.CharField(max_length=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='codBitacora',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Codigo Bitacora'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='codInstalacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.instalacion', verbose_name='Codigo Instalacion'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='estado',
            field=models.CharField(max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nivel_riesgo',
            field=models.CharField(choices=[('B', 'Bajo'), ('A', 'Alto')], default='B', max_length=20, verbose_name='Nivel de Riesgo'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='observaciones',
            field=models.CharField(max_length=100, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='ubicacion',
            field=models.CharField(max_length=40, verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='archivo',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('R', 'Rector'), ('CA', 'Coordinador Academico'), ('CC', 'Coordinador Convivencia'), ('P', 'Profesor'), ('S', 'Secretaria')], default='P', max_length=40, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codEmpleado',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Codigo Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='codadmin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tablas.admin', verbose_name='Codigo Admin'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='codInstalacion',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Codigo Instalacion'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='fecha_instalacion',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Fecha Instalacion'),
        ),
        migrations.AlterField(
            model_name='instalacion',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
