# Generated by Django 5.0.2 on 2024-04-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0005_usuario_alter_empleado_codadmin_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
