# Generated by Django 5.0.6 on 2024-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0006_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='archivopdf',
            field=models.FileField(null=True, upload_to='media/', verbose_name='PDF'),
        ),
    ]
