# Generated by Django 5.0.6 on 2024-05-27 02:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tablas', '0007_empleado_archivopdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='archivopdf',
        ),
        migrations.AddField(
            model_name='empleado',
            name='archivo_pdf',
            field=models.FileField(null=True, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='PDF'),
        ),
    ]
